title: Master Sword Restricted
version: v3.0
config:
- plugins:
  - use: split-format
    with:
      Shrines: "[.var(pad02:counter-shrine)] .prop(text)"
      Warps: "Warp .prop(text)"
- use: Pistonight/celer-presets/botw/most.yaml
- use: ../../common/config.yaml
route:
  use: ./main.yaml
