presets:
  HouseKeepingStuff:
    text: Check Resources =>
    notes:
    - "Arrows: .var(FireArrow) Fire; .var(IceArrow) Ice; .var(ShockArrow) Shock"
    - .var(Wood) Wood
    - .var(Hammer) Hammer Durability
    - Used .var(Amiibo) Fish Amiibos
  StatStuff:
    text: "SCW Stat: .var(SCW) SCWs, (.var(iSCW) infinity)"

tags:
  split-plat:
    background: black
    color: white
    split-type: Plateau
  split-end-game:
    background: black
    color: yellow
    split-type: End Game
  split-dark-beast:
    background: black
    color: yellow
    split-type: Dark Beast
  italic:
    italic: true

splits:
  - split-plat
  - split-end-game
  - split-dark-beast


icons:
  shrine-iscw: https://icons.pistonite.org/icon/shrine.blessing.none.2a767d.59ffff.2a767d.59ffff.2a767d.59ffff.png
  shrine-iscw-blessing: https://icons.pistonite.org/icon/shrine.blessing.none.2a767d.59ffff.2a767d.59ffff.2a767d.59ffff.png
  shrine-iscw-tos: https://icons.pistonite.org/icon/shrine.double_sword.none.2a767d.59ffff.2a767d.59ffff.2a767d.59ffff.png
  castle: https://icons.pistonite.org/icon/location.small_castle.none.633830.f0673a.633830.f0673a.633830.f0673a.png
  blights: https://icons.pistonite.org/icon/shrine.sword.none.f24c99.ffc0fa.f24c99.ffc0fa.f24c99.ffc0fa.png