# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    name: Publish
    strategy: 
      matrix:
        project:
          - adx
          - as33
          - as4
          - akm
          - aq
          - aq2

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Get bundle.json
        run: |
          mkdir publish
          cp projects/${{ matrix.project }}/bundle.json publish

      - name: Publish to branch
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: "${{ matrix.project }}"
          folder: publish
